import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createGuestApi} from '../public/guest.mjs';
import {PERIODS,createHandler} from '../server/handler.mjs';
const bank=JSON.parse(readFileSync(new URL('../data/content.json',import.meta.url),'utf8'));
class Storage {constructor(){this.values=new Map();}getItem(k){return this.values.get(k)||null;}setItem(k,v){this.values.set(k,v);}}
function fixture(storage=new Storage()){let time=Date.UTC(2026,9,7);const api=createGuestApi({bank,periods:PERIODS,contentVersion:'v1',storage,clock:()=>time});return {api,storage,advance:ms=>time+=ms,now:()=>time};}
async function complete(f,id,w){const a=await f.api('/api/attempts/start',{childId:id,week:w});for(const q of bank.weeks[w-1].questions)await f.api('/api/answer',{attemptId:a.id,question:q.id,choice:q.answer});return f.api('/api/complete',{attemptId:a.id});}
test('anonymous curriculum endpoints need neither login nor DB, but family records remain protected',async()=>{const handler=createHandler({bank,contentVersion:'v1'});for(const path of ['/api/guest-content','/api/time']){const r=await handler.fetch(new Request('https://test.site'+path),{});assert.equal(r.status,200);}for(const path of ['/api/state','/api/export?childId=any','/api/report?childId=any&period=y1'])assert.equal((await handler.fetch(new Request('https://test.site'+path),{})).status,401);});
test('guest progress survives reload, separates children, enforces seven days and preserves first completion',async()=>{const f=fixture(),id=(await f.api('/api/profiles',{name:'An'})).id;const a=await f.api('/api/attempts/start',{childId:id,week:1});await f.api('/api/answer',{attemptId:a.id,question:1,choice:'C'});const fresh=createGuestApi({bank,periods:PERIODS,contentVersion:'v1',storage:f.storage,clock:f.now});assert.equal((await fresh('/api/attempt?id='+a.id)).questions[0].selected,'C');const first=await complete(f,id,1);await assert.rejects(f.api('/api/attempts/start',{childId:id,week:2}));f.advance(1000);assert.equal((await complete(f,id,1)).firstCompletedAt,first.firstCompletedAt);f.advance(604800000-1001);await assert.rejects(f.api('/api/attempts/start',{childId:id,week:2}));f.advance(1);assert.equal((await f.api('/api/attempts/start',{childId:id,week:2})).week,2);const second=(await f.api('/api/profiles',{name:'Bình'})).id;const state=await f.api('/api/state');assert.equal(Object.keys(state.profiles.find(p=>p.id===second).completions).length,0);assert.equal(Object.keys(state.profiles.find(p=>p.id===id).completions).length,1);});
test('52-week guest journey, assessment history, report and backup restoration',async()=>{const f=fixture(),id=(await f.api('/api/profiles',{name:'Mít'})).id;for(let w=1;w<=52;w++){if(w>1)f.advance(604800000);await complete(f,id,w);}for(const period of ['m1','q1','y1'])await f.api('/api/assessment',{childId:id,period,ratings:{1:2},evidence:{1:'Con giúp bạn.'},note:'Ghi nhận nỗ lực.',nextStep:'Cùng đọc sách.',requestId:crypto.randomUUID()});const report=await f.api('/api/report?childId='+id+'&period=y1');assert.equal(report.summary.completedWeeks,52);assert.equal(report.summary.firstAnswered,520);assert.equal(report.assessment.ratings[1],2);const backup=await f.api('/api/export?childId='+id);assert.equal(backup.assessments.length,3);const other=fixture();other.advance(52*604800000);await other.api('/api/import',{backup});const restored=await other.api('/api/report?childId='+id+'&period=y1');assert.deepEqual(restored.summary,report.summary);assert.equal(restored.assessment.note,report.assessment.note);const broken=structuredClone(backup);broken.answers[0].choice='X';await assert.rejects(other.api('/api/import',{backup:broken}));assert.deepEqual((await other.api('/api/report?childId='+id+'&period=y1')).summary,report.summary);});
test('failed browser persistence does not pretend the answer was saved',async()=>{const f=fixture(),id=(await f.api('/api/profiles',{name:'An'})).id,a=await f.api('/api/attempts/start',{childId:id,week:1});f.storage.setItem=()=>{throw Error('quota');};await assert.rejects(f.api('/api/answer',{attemptId:a.id,question:1,choice:'C'}),/chưa thể lưu/);assert.equal((await f.api('/api/attempt?id='+a.id)).questions[0].selected,undefined);});
