import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {BIOMES,islandPosition,canVisit,adjacentWeek,worldNodes} from './world-model.mjs';
export {BIOMES};
export function mountWorld({container,weeks,getStatus,initialWeek=1,onSelect,onCollect,onEnter,onError,motion=true}){
  const systemReduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let reduced=systemReduced||!motion,paused=false;
  let renderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});}catch{onError('Thiết bị này chưa hỗ trợ 3D. Con vẫn có thể khám phá đủ 52 tuần bằng bản đồ 2D.');return null;}
  renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setClearColor(0xd9eee9);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
  renderer.domElement.setAttribute('aria-label','Bản đồ 3D: chạm một đảo để chọn nhiệm vụ. Có thể dùng phím mũi tên và Enter.');renderer.domElement.tabIndex=0;container.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xd9eee9,65,145);
  const camera=new THREE.OrthographicCamera(-24,24,18,-18,.1,200),controls=new OrbitControls(camera,renderer.domElement);
  controls.enableDamping=!reduced;controls.dampingFactor=.075;controls.minZoom=.5;controls.maxZoom=2.8;controls.maxPolarAngle=Math.PI*.46;controls.minPolarAngle=.25;controls.enablePan=true;
  const hemi=new THREE.HemisphereLight(0xffffff,0x729593,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff1cf,3.2);sun.position.set(-15,35,18);scene.add(sun);
  const materialCache=new Map(),batches=new Map(),resources=new Set(),pickable=[],islands=new Map(),floating=[];
  const material=(color,extra={})=>{const key=color+JSON.stringify(extra);if(!materialCache.has(key))materialCache.set(key,new THREE.MeshStandardMaterial({color,roughness:.85,flatShading:true,...extra}));return materialCache.get(key);};
  const geo={ball:new THREE.IcosahedronGeometry(1,1),rock:new THREE.IcosahedronGeometry(1,0),cone:new THREE.ConeGeometry(1,1,7),cylinder:new THREE.CylinderGeometry(1,1,1,8),box:new THREE.BoxGeometry(1,1,1)};
  const staticPiece=(geometry,color,position,scale=[1,1,1],rotation=[0,0,0])=>{const clone=geometry.index?geometry.toNonIndexed():geometry.clone(),matrix=new THREE.Matrix4().compose(new THREE.Vector3(...position),new THREE.Quaternion().setFromEuler(new THREE.Euler(...rotation)),new THREE.Vector3(...scale));clone.applyMatrix4(matrix);if(!batches.has(color))batches.set(color,[]);batches.get(color).push(clone);};
  const mesh=(geometry,color,position,scale=[1,1,1],parent=scene)=>{const obj=new THREE.Mesh(geometry,material(color));obj.position.set(...position);obj.scale.set(...scale);parent.add(obj);return obj;};
  const tree=(x,y,z,biome,size=1)=>{staticPiece(geo.cylinder,0x99745d,[x,y+size*.65,z],[.16*size,1.4*size,.16*size]);staticPiece(geo.ball,biome.leaf,[x,y+size*1.9,z],[.85*size,1.1*size,.85*size]);staticPiece(geo.ball,biome.grass,[x+.4*size,y+size*2.35,z],[.5*size,.6*size,.5*size]);};
  function label(text,color=0x315c50){const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d');if(!ctx)return null;ctx.fillStyle='#fffdf4';ctx.beginPath();ctx.arc(64,64,46,0,Math.PI*2);ctx.fill();ctx.lineWidth=5;ctx.strokeStyle='#'+color.toString(16).padStart(6,'0');ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.font='bold 44px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,64,65);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;resources.add(texture);const mat=new THREE.SpriteMaterial({map:texture,depthWrite:false});resources.add(mat);return new THREE.Sprite(mat);}
  const nodes=worldNodes(weeks,getStatus);
  for(const node of nodes){const [x,y,z]=node.position,biome=BIOMES[node.quarter],visited=node.status==='done',open=node.status==='open',locked=!canVisit(node.status);
    const ground=mesh(new THREE.CylinderGeometry(2,1.85,.5,10),locked?0xb1c2b9:biome.grass,[x,y-.25,z]);resources.add(ground.geometry);ground.userData={type:'island',week:node.week};pickable.push(ground);islands.set(node.week,{ground,position:new THREE.Vector3(x,y,z),status:node.status});
    staticPiece(geo.cone,locked?0xa5aaa6:biome.rock,[x,y-2.3,z],[1.85,4,1.85],[0,0,Math.PI]);
    for(let r=0;r<3;r++){const a=r*2.4+node.week;staticPiece(geo.rock,locked?0xc2c9c0:0xe4d3b4,[x+Math.cos(a)*1.35,y+.15,z+Math.sin(a)*1.3],[.3,.3+r*.06,.3]);}
    if(visited){tree(x-.35,y,z-.35,biome,1);for(let k=0;k<4;k++){const a=k*1.6;staticPiece(geo.ball,[0xffc3ae,0xffe8a4,0xdbb7ee,0xe9d699][k],[x+Math.cos(a)*1.2,y+.25,z+Math.sin(a)*1.2],[.19,.3,.19]);}}
    else if(open){staticPiece(geo.cylinder,0xb9895a,[x,y+.3,z],[.1,.6,.1]);staticPiece(geo.ball,biome.leaf,[x-.2,y+.6,z],[.35,.12,.2]);staticPiece(geo.ball,biome.grass,[x+.2,y+.8,z],[.35,.12,.2]);}
    else staticPiece(geo.rock,0x839f90,[x,y+.3,z],[.3,.45,.3]);
    const sign=label(String(node.week).padStart(2,'0'),visited?0x4c9564:open?0xbc903b:0x879890);if(sign){sign.position.set(x,y+3.2,z);sign.scale.set(2,2,1);sign.userData={type:'island',week:node.week};scene.add(sign);pickable.push(sign);}
    if(node.week<52){const next=islandPosition(node.week+1),curve=new THREE.QuadraticBezierCurve3(new THREE.Vector3(x,y-.05,z),new THREE.Vector3((x+next[0])/2,Math.max(y,next[1])+.4,(z+next[2])/2),new THREE.Vector3(...next));const line=new THREE.TubeGeometry(curve,12,.065,4,false);const isDone=node.status==='done';staticPiece(line,isDone?0xf1d18a:0xb6cac0,[0,0,0]);line.dispose();}
  }
  for(let q=0;q<4;q++){const biome=BIOMES[q],[x,z]=biome.center;staticPiece(geo.cylinder,biome.grass,[x,-.8,z],[5.4,.7,5.4]);staticPiece(geo.cone,biome.rock,[x,-4,z],[5.1,6,5.1],[0,0,Math.PI]);
    if(q===0){tree(x,-.45,z,biome,2.4);tree(x+3,-.45,z+1,biome,.7);tree(x-3,-.45,z-1,biome,.7);}
    if(q===1){for(let b=0;b<3;b++){staticPiece(geo.box,[0xddb8ec,0xf3d5ab,0xaacbd5][b],[x, b*.6,z],[4,.5,2.8],[0,b*.2,0]);}staticPiece(geo.box,0xf9f2dc,[x-1,2.2,z],[1.8,.16,2.6],[0,0,-.2]);staticPiece(geo.box,0xf9f2dc,[x+1,2.2,z],[1.8,.16,2.6],[0,0,.2]);tree(x+3,-.45,z+1,biome,.8);}
    if(q===2){for(let i=0;i<7;i++){const a=i*Math.PI*2/7;staticPiece(geo.ball,biome.accent,[x+Math.cos(a)*1.9,1.6,z+Math.sin(a)*1.9],[.85,.9,.85]);}staticPiece(geo.ball,0xffe3a0,[x,1.6,z],[1.1,1,1.1]);staticPiece(geo.cylinder,biome.leaf,[x,.3,z],[.3,2,.3]);tree(x-3,-.45,z+1,biome,.8);}
    if(q===3){staticPiece(geo.box,0xf7e3bd,[x,.65,z],[3,2.4,3]);for(let i=0;i<4;i++){const dx=i%2?1.7:-1.7,dz=i>1?1.7:-1.7;staticPiece(geo.cylinder,0xf3e6ce,[x+dx,1.5,z+dz],[.55,3.8,.55]);staticPiece(geo.cone,0xdba794,[x+dx,3.75,z+dz],[.9,1.1,.9]);}staticPiece(geo.cone,0xd4ad7a,[x,2.75,z],[2.5,1.9,2.5]);}
    for(let i=0;i<6;i++){const a=i;staticPiece(geo.ball,0x81b49b,[x+Math.cos(a)*4,-.1,z+Math.sin(a)*4],[.6,.55,.6]);}
  }
  for(const [color,parts]of batches){const merged=mergeGeometries(parts);parts.forEach(p=>p.dispose());if(merged){resources.add(merged);scene.add(new THREE.Mesh(merged,material(color)));}}
  const clouds=[];for(let i=0;i<12;i++){const group=new THREE.Group(),x=Math.sin(i*6.7)*44,z=Math.cos(i*8.1)*45;for(let c=0;c<3;c++)mesh(geo.ball,0xf6faf0,[c*1.4,Math.sin(c)*.2,0],[1.6,1,1.2],group);group.position.set(x,-4-i%3,z);scene.add(group);clouds.push({group,phase:i});}
  const player=new THREE.Group();mesh(geo.ball,0xffd9a4,[0,1.05,0],[.4,.42,.4],player);mesh(geo.cylinder,0x497e6b,[0,.48,0],[.36,.6,.36],player);mesh(geo.ball,0x34745c,[0,1.43,0],[.43,.15,.43],player);mesh(geo.ball,0x6ea36c,[.22,1.58,0],[.23,.09,.13],player);for(const dx of[-.15,.15])mesh(geo.ball,0x343e33,[dx,1.08,.355],[.045,.06,.045],player);for(const dx of[-.22,.22])mesh(geo.ball,0xe3b376,[dx,.06,0],[.18,.13,.25],player);for(const dx of[-.42,.42])mesh(geo.ball,0xffd9a4,[dx,.5,0],[.12,.16,.12],player);
  const glider=mesh(geo.ball,0xf6ce76,[0,-.06,0],[.9,.13,.65],player);scene.add(player);
  const halo=mesh(new THREE.TorusGeometry(2.18,.07,5,48),0xffedbd,[0,0,0]);halo.rotation.x=Math.PI/2;resources.add(halo.geometry);
  const sparkGeo=new THREE.IcosahedronGeometry(.17,0),sparkMat=new THREE.MeshBasicMaterial({color:0xffeea6});resources.add(sparkGeo);resources.add(sparkMat);let sparks=[],collected=0,particles=[];
  let selected=initialWeek,disposed=false,raf=0,lastFrame=0,dirty=true,focusTween=null,travel=null,elapsed=0;
  const spawnSparks=()=>{for(const s of sparks){scene.remove(s.mesh);const i=pickable.indexOf(s.mesh);if(i>=0)pickable.splice(i,1);}sparks=[];collected=0;onCollect?.(0);if(!canVisit(islands.get(selected).status))return;const pos=islands.get(selected).position;for(let i=0;i<3;i++){const a=i*Math.PI*2/3,s=mesh(sparkGeo,0xffef9f,[pos.x+Math.cos(a)*2.5,pos.y+2,pos.z+Math.sin(a)*2.5]);s.material=sparkMat;s.userData={type:'spark',index:i};sparks.push({mesh:s,base:s.position.clone(),phase:i});pickable.push(s);}};
  const focus=(point,overview=false)=>{const target=new THREE.Vector3(point.x,point.y,point.z),distance=overview?65:27;const destination=target.clone().add(new THREE.Vector3(distance,distance*1.16,distance*.96));if(reduced){camera.position.copy(destination);controls.target.copy(target);camera.zoom=overview?.7:1;camera.updateProjectionMatrix();}else focusTween={from:camera.position.clone(),to:destination,start:controls.target.clone(),target,t:0,zoom:overview?.7:1,startZoom:camera.zoom};dirty=true;};
  const select=(id,move=true)=>{selected=id;const island=islands.get(id);halo.position.copy(island.position).add(new THREE.Vector3(0,.11,0));onSelect(id);spawnSparks();focus(island.position);if(move&&canVisit(island.status)){if(reduced)player.position.copy(island.position);else travel={start:player.position.clone(),target:island.position.clone(),t:0};}dirty=true;};
  const spawnWeek=canVisit(islands.get(initialWeek).status)?initialWeek:nodes.find(n=>n.status==='open')?.week||nodes.filter(n=>n.status==='done').at(-1)?.week||1;
  player.position.copy(islands.get(spawnWeek).position);const quarter=Math.floor((initialWeek-1)/13),[cx,cz]=BIOMES[quarter].center;camera.position.set(cx+27,32,cz+27);controls.target.set(cx,0,cz);select(initialWeek,false);focusTween=null;controls.target.set(cx,0,cz);
  function collect(index){const spark=sparks.find(s=>s.mesh.userData.index===index);if(!spark)return;sparks=sparks.filter(s=>s!==spark);scene.remove(spark.mesh);pickable.splice(pickable.indexOf(spark.mesh),1);collected++;onCollect?.(collected);if(!reduced){for(let i=0;i<10;i++){const p=new THREE.Mesh(sparkGeo,sparkMat);p.position.copy(spark.mesh.position);scene.add(p);particles.push({mesh:p,velocity:new THREE.Vector3(Math.sin(i)*1.5,1+Math.cos(i),Math.cos(i)*1.5),age:0});}}dirty=true;}
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let pointerDown=null;
  const down=e=>{if(paused)return;renderer.domElement.focus({preventScroll:true});pointerDown={x:e.clientX,y:e.clientY};};
  const up=e=>{const start=pointerDown;pointerDown=null;if(paused||!start||Math.hypot(e.clientX-start.x,e.clientY-start.y)>8)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(pickable)[0];if(hit){if(hit.object.userData.type==='spark')collect(hit.object.userData.index);else select(hit.object.userData.week);}};
  const key=e=>{if(paused)return;const deltas={ArrowLeft:-1,ArrowRight:1,ArrowUp:-13,ArrowDown:13};if(deltas[e.key]){e.preventDefault();select(adjacentWeek(selected,deltas[e.key]));}else if(e.key==='Enter'&&canVisit(islands.get(selected).status)){e.preventDefault();onEnter(selected);}else if(e.key===' '){e.preventDefault();if(!travel&&!reduced)travel={start:player.position.clone(),target:player.position.clone(),t:0,hop:true};}};
  renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('keydown',key);
  controls.addEventListener('start',()=>{focusTween=null;});controls.addEventListener('change',()=>{dirty=true;});
  const resize=()=>{if(disposed)return;const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);const aspect=w/h;camera.left=-18*aspect;camera.right=18*aspect;camera.top=18;camera.bottom=-18;camera.updateProjectionMatrix();dirty=true;};const observer=new ResizeObserver(resize);observer.observe(container);resize();
  const contextLost=e=>{e.preventDefault();onError('3D đang tạm dừng trên thiết bị này. Mở danh sách nhiệm vụ để tiếp tục bài học.');dispose();};renderer.domElement.addEventListener('webglcontextlost',contextLost);
  function animate(time){if(disposed)return;raf=requestAnimationFrame(animate);if(document.hidden||paused){lastFrame=time;return;}const dt=Math.min((time-lastFrame)/1000,.07);if(time-lastFrame<1000/35)return;lastFrame=time;elapsed+=dt;controls.update();if(focusTween){const f=focusTween;f.t=Math.min(1,f.t+dt*1.5);const t=f.t*f.t*(3-2*f.t);camera.position.lerpVectors(f.from,f.to,t);controls.target.lerpVectors(f.start,f.target,t);camera.zoom=THREE.MathUtils.lerp(f.startZoom,f.zoom,t);camera.updateProjectionMatrix();dirty=true;if(f.t===1)focusTween=null;}
    if(travel){travel.t=Math.min(1,travel.t+dt*(travel.hop?1.7:.8));const t=travel.t*travel.t*(3-2*travel.t);player.position.lerpVectors(travel.start,travel.target,t);player.position.y+=Math.sin(travel.t*Math.PI)*(travel.hop?1.8:5);glider.visible=!travel.hop;const direction=travel.target.clone().sub(travel.start);if(direction.lengthSq()>.01)player.rotation.y=Math.atan2(direction.x,direction.z);if(travel.t===1){travel=null;glider.visible=false;}dirty=true;}
    if(!reduced){clouds.forEach(c=>{c.group.position.y=-5+Math.sin(elapsed*.25+c.phase)*.5;});sparks.forEach(s=>{s.mesh.position.y=s.base.y+Math.sin(elapsed*1.8+s.phase)*.25;s.mesh.rotation.y=elapsed;});halo.scale.setScalar(1+Math.sin(elapsed*2)*.025);if(!travel)player.children[0].rotation.z=Math.sin(elapsed)*.025;dirty=true;}
    for(const p of particles){p.age+=dt;p.mesh.position.addScaledVector(p.velocity,dt);p.mesh.scale.setScalar(Math.max(0,1-p.age));}particles=particles.filter(p=>{if(p.age>1){scene.remove(p.mesh);return false;}return true;});if(dirty){renderer.render(scene,camera);dirty=false;}}
  glider.visible=false;raf=requestAnimationFrame(animate);
  function dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('keydown',key);renderer.domElement.removeEventListener('webglcontextlost',contextLost);scene.traverse(obj=>{if(obj.geometry)resources.add(obj.geometry);if(obj.material){if(Array.isArray(obj.material))obj.material.forEach(m=>resources.add(m));else resources.add(obj.material);}});Object.values(geo).forEach(g=>resources.add(g));resources.forEach(r=>r.dispose());materialCache.forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove();}
  return {setPaused(value){paused=!!value;controls.enabled=!paused;pointerDown=null;},setMotion(value){reduced=systemReduced||!value;controls.enableDamping=!reduced;if(reduced){if(travel)player.position.copy(travel.target);travel=null;glider.visible=false;if(focusTween){camera.position.copy(focusTween.to);controls.target.copy(focusTween.target);camera.zoom=focusTween.zoom;camera.updateProjectionMatrix();focusTween=null;}particles.forEach(p=>scene.remove(p.mesh));particles=[];halo.scale.setScalar(1);dirty=true;}},select,collectNext(){const next=sparks[0];if(next)collect(next.mesh.userData.index);},focusQuarter(q){const [x,z]=BIOMES[q].center;focus(new THREE.Vector3(x,0,z));},overview(){focus(new THREE.Vector3(0,0,0),true);},dispose};
}
export {mountQuiz} from './quiz.mjs';
export {mountAtrium} from './atrium.mjs';
